# yaml-language-server: $schema=https://cdn.jsdelivr.net/gh/compose-spec/compose-spec@master/schema/compose-spec.json

services:
  app: # common use case is to run shell or execute commands
    build: &app-build {dockerfile: Dockerfile, target: develop}
    environment:
      HOME: /tmp
      LOG_LEVEL: debug
    working_dir: /src
    volumes: [.:/src:rw, app-tmp-data:/tmp:rw, app-modules-cache:/var/tmp/go:rw]
    security_opt: [no-new-privileges:true]

  app-bot:
    build: *app-build
    env_file: [{path: .env, required: false}]
    entrypoint: sh -c 'go build -buildvcs=false -o /var/tmp/app ./cmd/video-dl-bot/ && exec $0 "$@"'
    command: /var/tmp/app # --flags-goes-here
    volumes: [.:/src:rw]
    security_opt: [no-new-privileges:true]

volumes:
  app-modules-cache: {}
  app-tmp-data: {}
